# Verwende ein Node.js-Image als Basis
FROM node:16

# Setze das Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere die package.json und installiere die Abhängigkeiten
COPY package*.json ./
RUN npm install

# Kopiere den gesamten Quellcode in den Container
COPY . .

# Exponiere den Port, auf dem der Server läuft
EXPOSE 5000

# Starte den Server
CMD ["node", "server.js"]
